FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
COPY . .
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common 
RUN pip install --upgrade pip 
RUN pip install wheel setuptools pip --upgrade

RUN pip install -r requirements.txt


EXPOSE 8501
ENTRYPOINT ["streamlit","run","Marketing_project.py" ,"--server.port=8501", "--server.address=0.0.0.0"]